### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by piquepq** [Sandbergo/branch2learn#1]
python branch2learn/02_train.py -p $PROBLEM -m $MODEL -g $DEVICE
[11-06 21:30:28.11] Model:   mlp2
[11-06 21:30:28.11] Problem: setcover
[11-06 21:30:28.11] Device:  cpu
[11-06 21:30:28.11] Lr:      0.001
[11-06 21:30:28.11] Epochs:  100
/home/pq/anaconda3/envs/myenv/lib/python3.9/site-packages/torch_geometric/deprecation.py:13: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
[11-06 21:30:28.15] Beginning training
Traceback (most recent call last):
  File "/home/pq/branch2learn-main/branch2learn/02_train.py", line 101, in <module>
    train_loss, train_acc = process(
  File "/home/pq/branch2learn-main/branch2learn/utilities/model.py", line 76, in process
    for batch in data_loader:
  File "/home/pq/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/pq/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/pq/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/pq/anaconda3/envs/myenv/lib/python3.9/site-packages/torch_geometric/loader/dataloader.py", line 39, in __call__
    return self.collate(batch)
  File "/home/pq/anaconda3/envs/myenv/lib/python3.9/site-packages/torch_geometric/loader/dataloader.py", line 19, in collate
    return Batch.from_data_list(batch, self.follow_batch,
  File "/home/pq/anaconda3/envs/myenv/lib/python3.9/site-packages/torch_geometric/data/batch.py", line 69, in from_data_list
    batch, slice_dict, inc_dict = collate(
  File "/home/pq/anaconda3/envs/myenv/lib/python3.9/site-packages/torch_geometric/data/collate.py", line 33, in collate
    out = cls(_base_cls=data_list[0].__class__)  # Dynamic inheritance.
  File "/home/pq/anaconda3/envs/myenv/lib/python3.9/site-packages/torch_geometric/data/batch.py", line 41, in __call__
    return super(DynamicInheritance, new_cls).__call__(*args, **kwargs)
  File "/home/pq/branch2learn-main/branch2learn/utilities/data.py", line 31, in __init__
    self.nb_candidates = len(candidates)
TypeError: object of type 'NoneType' has no len()

**Comment by Sandbergo** [comment]
Hello,

It seems that `BipartiteNodeData()` is called with `None`, and the most likely explanation is an issue with the sample pickle files.

I unfortunately do not have a working setup to test the scripts, so here are a few things I recommend you to test out:
1. Verify that `sample_x.pkl` files exist in `data/samples/${PROBLEM}/train/`
2. Verify that the samples are loaded in `02_train.py`
3. Test out the alternative data generation scripts by running:
```
python branch2learn/00_generate_instances.py -p $PROBLEM
python branch2learn/01b_generate_data_alt.py -p $PROBLEM
```
4. Check if you can run the ecole example at https://github.com/ds4dm/ecole/blob/master/examples/branching-imitation.ipynb

I have made a small change to let the user know the number of samples that are trained and validated on before starting training.

Please let me know if and how you have solved the issue, and feel free to send a pull request if you can.

Best regards, 
Lars

**Comment by monkeymahy** [comment]
$ python branch2learn/02_train.py -m gnn1 -p setcover
[08-28 16:09:41.12] Model:   gnn1
[08-28 16:09:41.12] Problem: setcover
[08-28 16:09:41.12] Device:  cuda
[08-28 16:09:41.12] Lr:      0.001
[08-28 16:09:41.12] Epochs:  100
[08-28 16:09:41.31] Training with 50000 samples, validating with 10000 samples
/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch_geometric/deprecation.py:12: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
[08-28 16:09:41.32] Beginning training
Traceback (most recent call last):
  File "/mnt/e/PythonProject/branch2learn-main/branch2learn/02_train.py", line 125, in <module>
    train_loss, train_acc = process(
  File "/mnt/e/PythonProject/branch2learn-main/branch2learn/utilities/model.py", line 80, in process
    for batch in data_loader:
  File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch_geometric/loader/dataloader.py", line 19, in __call__
    return Batch.from_data_list(batch, self.follow_batch,
  File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch_geometric/data/batch.py", line 76, in from_data_list
    batch, slice_dict, inc_dict = collate(
  File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch_geometric/data/collate.py", line 84, in collate
    value, slices, incs = _collate(attr, values, data_list, stores,
  File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch_geometric/data/collate.py", line 133, in _collate
    incs = get_incs(key, values, data_list, stores)
  File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch_geometric/data/collate.py", line 262, in get_incs
    repeats = [
  File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch_geometric/data/collate.py", line 263, in <listcomp>
    data.__inc__(key, value, store)
TypeError: BipartiteNodeData.__inc__() takes 3 positional arguments but 4 were given
