### ISSUE TITLE
TypeError: BipartiteNodeData.inc() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by monkeymahy** [Sandbergo/branch2learn#2]
$ python branch2learn/02_train.py -m gnn1 -p setcover
[08-28 16:09:41.12] Model: gnn1
[08-28 16:09:41.12] Problem: setcover
[08-28 16:09:41.12] Device: cuda
[08-28 16:09:41.12] Lr: 0.001
[08-28 16:09:41.12] Epochs: 100
[08-28 16:09:41.31] Training with 50000 samples, validating with 10000 samples
/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch_geometric/deprecation.py:12: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
warnings.warn(out)
[08-28 16:09:41.32] Beginning training
Traceback (most recent call last):
File "/mnt/e/PythonProject/branch2learn-main/branch2learn/02_train.py", line 125, in
train_loss, train_acc = process(
File "/mnt/e/PythonProject/branch2learn-main/branch2learn/utilities/model.py", line 80, in process
for batch in data_loader:
File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 681, in next
data = self._next_data()
File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
data = self._dataset_fetcher.fetch(index) # may raise StopIteration
File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
return self.collate_fn(data)
File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch_geometric/loader/dataloader.py", line 19, in call
return Batch.from_data_list(batch, self.follow_batch,
File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch_geometric/data/batch.py", line 76, in from_data_list
batch, slice_dict, inc_dict = collate(
File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch_geometric/data/collate.py", line 84, in collate
value, slices, incs = _collate(attr, values, data_list, stores,
File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch_geometric/data/collate.py", line 133, in _collate
incs = get_incs(key, values, data_list, stores)
File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch_geometric/data/collate.py", line 262, in get_incs
repeats = [
File "/home/mahaoyuan/miniconda3/envs/ecole/lib/python3.10/site-packages/torch_geometric/data/collate.py", line 263, in
data.inc(key, value, store)
TypeError: BipartiteNodeData.inc() takes 3 positional arguments but 4 were given

**Comment by monkeymahy** [comment]
i fixed this by by adjusting the function headers to:
def __inc__(self, key, value, *args, **kwargs):

**Comment by Sandbergo** [comment]
Thank you for the issue and fix! This is due to changes in pytorch-geometric version 1 to 2, but you can consult https://github.com/ds4dm/ecole/blob/master/examples/branching-imitation/example.ipynb where they have made this update. I am closing this issue, as the install script specifies torch-geometric version 1.8, but I may update my code to newer versions in the future.
